--- name:default
# defaults to unset, so not taken into account
final_heading: .nan
# no documentation available for this property
geometrical_resolution: 0.1
# If the is not set, the next position is take either from step_with from the current location based,
# independat if the vehicle might jup on the spline. For calculation the NEXT position to the spline for the vehicle is taken
# if this is set, the value indicates the maximum-allowed jump-value on the spline. This means the spline is started at the beginning, and the allowed
# next position on the spline cannot be more far away than this property. The result will be that the vehicle follows the complete spline from beginning to end
# independant id another spoint of the spline is closer to the vehicle.
max_spline_jump_distance: 3
# no documentation available for this property
step_width: 2.0
# no documentation available for this property
timeout_at_end_before_mark_end_reached: 10.0
# use the zero heading for debuggin, instead calculated heading
use_zero_heading: false
--- name:hall_square
trajectory:
  speed: 1
  spline:
    geometric_resolution: 0.1
    dimension: 3
    curve_order: 3
    kind: :POLYNOMIAL_BSPLINE
    knots:
    - 0.0
    - 0.0
    - 0.0
    - 21.402295979079504
    - 38.89508823891228
    - 38.89508823891228
    - 38.89508823891228
    vertices:
    - 6.0
    - 4.0
    - -5.0
    - -14.092692070806969
    - 10.488859875419607
    - 2.6141634687526523
    - -4.85338528528596
    - -8.726471397007122
    - -10.50961038305679
    - 6.0
    - -4.0
    - -4.0
--- name:hall_cool
trajectory:
  speed: 3.2328802e-316
  spline:
    geometric_resolution: 0.1
    dimension: 3
    curve_order: 3
    kind: :POLYNOMIAL_BSPLINE
    knots:
    - 0.0
    - 0.0
    - 0.0
    - 11.129727453672533
    - 19.716454379523462
    - 27.30549869193595
    - 38.09610512306486
    - 38.09610512306486
    - 38.09610512306486
    vertices:
    - 0.0
    - 0.0
    - -5.0
    - 6.805716897834794
    - 7.641252559728969
    - -7.958966482116211
    - -1.256314266800452
    - -4.676057746945258
    - 0.4610220594102259
    - -7.156029268416774
    - -5.009770119462755
    - -8.884569939188419
    - -4.014107843006529
    - 8.019259978524778
    - -3.1817687032577506
    - 0.0
    - 0.0
    - -1.0
