--- name:default
# radius of the buoy in m
buoy_radius: 0.2
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 20
# debugging or not?
debug: true
# Sets test mode.
debug_gui: true
# the time in s how long a buoy of the past is noticed by the filter.
filter_timeout: 1.5
# Hough threshold.
hHoughAccumulatorThreshold: 40
# Hough threshold.
hHoughEdgeThreshold: 30
# no documentation available for this property
hSmooth: 75
# Buoy hue value.
hValueMax: 255
# Buoy hue value.
hValueMin: 25 
# Buoy saturation value.
houghMaxCircle: 150
# Buoy hue value.
houghMinCircle: 20
# no documentation available for this property
hough_debug_h: false
# no documentation available for this property
hough_debug_s: false
# no documentation available for this property
hough_debug_v: false
# no documentation available for this property
hsv_gray: 0
# for light detection: retion of interrest height
roi_height: 3.0
# for light detection: retion of interrest width
roi_width: 3.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_x: 0.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_y: 0.2
# Hough threshold.
sHoughAccumulatorThreshold: 40
# Hough threshold.
sHoughEdgeThreshold: 30
# no documentation available for this property
sSmooth: 75
# Buoy saturation value.
sValueMax: 255
# Buoy saturation value.
sValueMin: 45
# no documentation available for this property
use_h: true
# no documentation available for this property
use_s: true
# no documentation available for this property
use_v: false
# Hough threshold.
vHoughAccumulatorThreshold: 19
# Hough threshold.
vHoughEdgeThreshold: 19
# no documentation available for this property
vSmooth: 23
# Buoy hue value.
vValueMax: 255
# Buoy hue value.
vValueMin: 200
--- name:simulation
# radius of the buoy in m
buoy_radius: 0.05
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 20
# debugging or not?
debug: true
# Sets test mode.
debug_gui: true
# the time in s how long a buoy of the past is noticed by the filter.
filter_timeout: 1.5
# Hough threshold.
hHoughAccumulatorThreshold: 25
# Hough threshold.
hHoughEdgeThreshold: 25
# no documentation available for this property
hSmooth: 17
# Buoy hue value.
hValueMax: 255
# Buoy hue value.
hValueMin: 55
# Buoy saturation value.
houghMaxCircle: 55
# Buoy hue value.
houghMinCircle: 10
# no documentation available for this property
hough_debug_h: false
# no documentation available for this property
hough_debug_s: false
# no documentation available for this property
hough_debug_v: false
# no documentation available for this property
hsv_gray: 0
# for light detection: retion of interrest height
roi_height: 3.0
# for light detection: retion of interrest width
roi_width: 3.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_x: 0.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_y: 0.2
# Hough threshold.
sHoughAccumulatorThreshold: 25
# Hough threshold.
sHoughEdgeThreshold: 25
# no documentation available for this property
sSmooth: 17
# Buoy saturation value.
sValueMax: 255
# Buoy saturation value.
sValueMin: 153
# no documentation available for this property
use_h: true
# no documentation available for this property
use_s: false
# no documentation available for this property
use_v: false
# Hough threshold.
vHoughAccumulatorThreshold: 25
# Hough threshold.
vHoughEdgeThreshold: 25
# no documentation available for this property
vSmooth: 13
# Buoy hue value.
vValueMax: 255
# Buoy hue value.
vValueMin: 200
--- name:bottom_orange 
# radius of the buoy in m
buoy_radius: 0.2
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 20
# debugging or not?
debug: false
# Sets test mode.
debug_gui: false
# the time in s how long a buoy of the past is noticed by the filter.
filter_timeout: 1.5
# Hough threshold.
hHoughAccumulatorThreshold: 40
# Hough threshold.
hHoughEdgeThreshold: 30
# no documentation available for this property
hSmooth: 40
# Buoy hue value.
hValueMax: 70
# Buoy hue value.
hValueMin: 1 
# Buoy saturation value.
houghMaxCircle: 150
# Buoy hue value.
houghMinCircle: 15
# no documentation available for this property
hough_debug_h: false
# no documentation available for this property
hough_debug_s: false
# no documentation available for this property
hough_debug_v: false
# no documentation available for this property
hsv_gray: 0
# for light detection: retion of interrest height
roi_height: 3.0
# for light detection: retion of interrest width
roi_width: 3.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_x: 0.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_y: 0.2
# Hough threshold.
sHoughAccumulatorThreshold: 40
# Hough threshold.
sHoughEdgeThreshold: 30
# no documentation available for this property
sSmooth: 75
# Buoy saturation value.
sValueMax: 255
# Buoy saturation value.
sValueMin: 30
# no documentation available for this property
use_h: true
# no documentation available for this property
use_s: false
# no documentation available for this property
use_v: false
# Hough threshold.
vHoughAccumulatorThreshold: 19
# Hough threshold.
vHoughEdgeThreshold: 19
# no documentation available for this property
vSmooth: 75
# Buoy hue value.
vValueMax: 255
# Buoy hue value.
vValueMin: 220
# Color of the Buoy
buoy_color: :ORANGE
--- name:bottom_white 
# radius of the buoy in m
buoy_radius: 0.2
# number of frames a buoy is not detected in order to set BUOY_LOST
buoy_timeout: 20
# debugging or not?
debug: true
# Sets test mode.
debug_gui: true
# the time in s how long a buoy of the past is noticed by the filter.
filter_timeout: 1.5
# Hough threshold.
hHoughAccumulatorThreshold: 40
# Hough threshold.
hHoughEdgeThreshold: 30
# no documentation available for this property
hSmooth: 40
# Buoy hue value.
hValueMax: 255
# Buoy hue value.
hValueMin: 15 
# Buoy saturation value.
houghMaxCircle: 150
# Buoy hue value.
houghMinCircle: 20
# no documentation available for this property
hough_debug_h: false
# no documentation available for this property
hough_debug_s: false
# no documentation available for this property
hough_debug_v: false
# no documentation available for this property
hsv_gray: 0
# for light detection: retion of interrest height
roi_height: 3.0
# for light detection: retion of interrest width
roi_width: 3.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_x: 0.0
# for light detection: relative region of interrest koordinate as factor of buoy-radius
roi_y: 0.2
# Hough threshold.
sHoughAccumulatorThreshold: 40
# Hough threshold.
sHoughEdgeThreshold: 30
# no documentation available for this property
sSmooth: 41
# Buoy saturation value.
sValueMax: 255
# Buoy saturation value.
sValueMin: 50
# no documentation available for this property
use_h: false
# no documentation available for this property
use_s: true
# no documentation available for this property
use_v: true
# Hough threshold.
vHoughAccumulatorThreshold: 19
# Hough threshold.
vHoughEdgeThreshold: 19
# no documentation available for this property
vSmooth: 41
# Buoy hue value.
vValueMax: 255
# Buoy hue value.
vValueMin: 210
# Color of the Buoy
buoy_color: :WHITE
