--- name:default
# start angle of the supposed wall detection range in the local frame
left_opening_angle:
  rad: 0.785
# end angle of the supposed wall detection range in the local frame
right_opening_angle:
  rad: 0.785
# the initial angle to the wall in the local coordinate frame
initial_wall_direction:
  rad: -1.57

# maximum distance of the measurements to the model line to be considered as inlier
ransac_max_distance: 0.3
# minimum amount of inliers the ransac line model should have
ransac_min_inlier: 0.5

# amount of wall candidates to check for stability
wall_candidate_count: 5
# maximum allowed sigma of the estimated wall angle
wall_distance_sigma: 0.2
# maximum allowed sigma of the estimated distance of the wall
wall_angle_sigma: 0.1

# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
# Time in s between sonarbeam_feature readings
sonarbeam_feature_period: 0.1
# Time in s between pose_samples readings
pose_samples_period: 0.01

# the global name that should be used for the internal wall frame
wall_frame: reference_wall
# the global name that should be used for the internal world frame
world_frame: world
# the global name that should be used for the internal odometry frame
odometry_frame: odometry
# the global name that should be used for the internal sonar frame
sonar_frame: sonar
# The target frame in the generated poses
target_frame: world_orientation

--- name:simulation
pose_samples_period: 0.1
wall_candidate_count: 5
