--- name:default
# ******************************
# ******** Frame Names *********
# ******************************
# the global name that should be used for the internal body frame
body_frame: body
# the global name that should be used for the internal imu frame
imu_frame: imu
# the global name that should be used for the internal lbl frame
lbl_frame: lbl
# the global name that should be used for the internal dvl frame
dvl_frame: dvl
# the global name that should be used for the internal pressure_sensor frame
pressure_sensor_frame: pressure_sensor
# The target frame in the generated poses. The source frame is the body frame (as declared in the transformer configuration)
target_frame: world

# ******************************
# *** Transformer Properties ***
# ******************************
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
# Time in s between velocity_samples readings
model_velocity_samples_period: 0.01
# Time in s between velocity_samples readings
dvl_velocity_samples_period: 0.083
# Time in s between orientation_samples readings
orientation_samples_period: 0.01
# Time in s between position_samples readings
lbl_position_samples_period: 0.01
# Time in s between position_samples readings
xy_position_samples_period: 0.01
# Time in s between depth_samples readings
depth_samples_period: 0.0625

# ******************************
# ***** Filter Properties ******
# ******************************
filter_type: :EKF
# no documentation available for this property
max_time_delta: 2.0

initial_state:
  position:
    data:
      - -10
      - 22
      - 0

--- name:avalon
lbl_frame: body
dvl_frame: body

--- name:dagon
lbl_frame: body


--- name:sauce
target_frame: map_sauce

--- name:halle
target_frame: map_halle
