--- name:default
# no documentation available for this property
average_fill: 0.7
# no documentation available for this property
speed_factor: 4.0
# no documentation available for this property
strave_speed: 0.7
# depth
depth: -4.0
lost_threashold: 0.1

