--- name:default
# no documentation available for this property
average_fill: 0.25
# no documentation available for this property
speed_factor: 4.0
# no documentation available for this property
strave_speed: 0.7
# depth
depth: -9.5
lost_threashold: 0.05

